web/router.ex
defmodule Myuserinfo.Router do
  use Myuserinfo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Myuserinfo do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/users", UserController
    #get "/users/:id", UserController, :show

    get     "/login",  SessionController, :new
    post    "/login",  SessionController, :create
    delete  "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Myuserinfo do
  #   pipe_through :api
  # end
end

lib/myuserinfo/endpoint.ex
defmodule Myuserinfo.Endpoint do
  use Phoenix.Endpoint, otp_app: :myuserinfo

  socket "/socket", Myuserinfo.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :myuserinfo, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_myuserinfo_key",
    signing_salt: "iSGeS61J"

  plug Myuserinfo.Router
end

lib/myuserinfo/repo.ex
defmodule Myuserinfo.Repo do
  use Ecto.Repo, otp_app: :myuserinfo
end

web/models/session.ex
defmodule Myuserinfo.Session do
  alias Myuserinfo.User
  #alias Myuserinfo.Userinf



  def current_user(conn) do
    id = Plug.Conn.get_session(conn, :current_user)
    if id, do: Myuserinfo.Repo.get(User, id)
  end

  def logged_in?(conn), do: !!current_user(conn)

end

web/models/user.ex
defmodule Myuserinfo.User do
  use Myuserinfo.Web, :model

  schema "users" do
    field :name, :string
    field :email, :string
    field :age, :integer
    field :sex, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :email, :age, :sex])
    |> validate_required([:name, :email, :age, :sex])
    |> validate_format(:email, ~r/@/)
    |> validate_inclusion(:age, 18..100)
    |> unique_constraint(:email)
  end
end

web/models/userinf.ex
defmodule Myuserinfo.Userinf do
  use Myuserinfo.Web, :model

  schema "userinfs" do
    field :password, :string
    field :mobile, :integer
    belongs_to :user, Myuserinfo.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:password, :mobile, :user_id])
    |> validate_required([:password, :mobile])
    |> validate_length(:password, min: 6)
    |> validate_length(:password, max: 25)
    |> unique_constraint(:mobile)
  end
end

web/controllers/page_controller.ex
defmodule Myuserinfo.PageController do
  use Myuserinfo.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/session_controller.ex
defmodule Myuserinfo.SessionController do
  use Myuserinfo.Web, :controller

  alias Myuserinfo.Userinf

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => session_params}) do
    case login(session_params, Myuserinfo.Repo) do
      {:ok, user} ->
        conn
        #|> put_session(:current_user, user.id)
        |> put_flash(:info, "Logged in")
        |> redirect(to: user_path(conn, :show, user.user_id))
      :error ->
        conn
        |> put_flash(:info, "Wrong Mobile No. or Password")
        |> render("new.html")
    end
  end

  def login(params, repo) do
      user = repo.get_by(Userinf, mobile: params["mobile"])
      if user do
          if user.password == params["password"] do
            {:ok, user}
          else
            :error
          end
      else
        :error
      end
  end

  def delete(conn, _) do
    conn
    |> delete_session(:current_user)
    |> put_flash(:info, "Logged out")
    |> redirect(to: "/users")
  end

end

web/controllers/user_controller.ex
defmodule Myuserinfo.UserController do
  use Myuserinfo.Web, :controller

  alias Myuserinfo.User
  alias Myuserinfo.Userinf

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    changeset2 = Userinf.changeset(%Userinf{})
    render(conn, "new.html", changeset: changeset, changeset2: changeset2)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)
    case Repo.insert(changeset) do
      {:ok, user} ->
        user_params = Map.put(user_params, "user_id" , user.id)
        changeset2 = Userinf.changeset(%Userinf{}, user_params)
        case Repo.insert(changeset2) do
          {:ok, _user} ->
            conn
            #|> put_session(:current_user, changeset.id)
            |> put_flash(:info, "Hey we have received your details.")
            |> redirect(to: user_path(conn, :index))
          {:error, changeset} ->
            render(conn, "new.html", changeset: changeset)
        end
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user, user_params)
    case Repo.update(changeset) do
      {:ok, user} ->
        user2 = Repo.get_by(Userinf, user_id: id)
        changeset2 = Userinf.changeset(user2, user_params)
        case Repo.update(changeset2) do
          {:ok, user} ->
          conn
          |> put_flash(:info, "User updated successfully.")
          |> redirect(to: user_path(conn, :show, user))
          {:error, changeset} ->
          render(conn, "edit.html", user: user, changeset: changeset)
        end
        {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id, "id" => user_id}) do
    user2 = Repo.get!(Userinf, user_id)
    user  = Repo.get!(User, id)
    Repo.delete!(user2)
    Repo.delete!(user)
    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end

end

web/views/error_view.ex
defmodule Myuserinfo.ErrorView do
  use Myuserinfo.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Myuserinfo.LayoutView do
  use Myuserinfo.Web, :view
end

web/views/page_view.ex
defmodule Myuserinfo.PageView do
  use Myuserinfo.Web, :view
end

web/views/session_view.ex
defmodule Myuserinfo.SessionView do
  use Myuserinfo.Web, :view
end

web/views/user_view.ex
defmodule Myuserinfo.UserView do
  use Myuserinfo.Web, :view

end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Myuserinfo!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/session/new.html.eex
<h2>User Login</h2>

<%= form_for @conn, session_path(@conn, :create), [name: :session], fn f -> %>
  <div class="form-group">
    <label>Mobile</label>
    <%= text_input f, :mobile, class: "form-control", required: "required" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control", required: "required" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form0.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

<%= link "Back to your home", to: user_path(@conn, :show, @  user) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p> Hey you did mistake, Kindly check your error </p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :age, class: "control-label" %>
    <%= text_input f, :age, class: "form-control", min: 18 %>
    <%= error_tag f, :age %>
  </div>

  <div class="form-group">
    <%= label f, :sex, class: "control-label" %>
    <%= text_input f, :sex, class: "form-control" %>
    <%= error_tag f, :sex %>
  </div>

  <div class="form-group">
    <%= label f, :mobile  , class: "control-label" %>
    <%= text_input f, :mobile, class: "form-control" %>
    <%= error_tag f, :mobile %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Sign Up", class: "btn btn-success" %>
  </div>
<% end %>

web/templates/user/form0.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p> Hey you did mistake, Kindly check your error </p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :age, class: "control-label" %>
    <%= text_input f, :age, class: "form-control", min: 18 %>
    <%= error_tag f, :age %>
  </div>

  <div class="form-group">
    <%= label f, :sex, class: "control-label" %>
    <%= text_input f, :sex, class: "form-control" %>
    <%= error_tag f, :sex %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Update", class: "btn btn-success" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<%= if logged_in?(@conn) do %>
  <li><%= current_user(@conn).email %></li>
  <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
  <br><br>
  <h3>My Users </h3>
  <table class="table">
    <thead>
      <tr>
        <th>S. No.</th>
        <th>Name</th>
        <th>Email</th>
        <th>Age</th>
        <th>Sex</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= for user <- @users do %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.age %></td>
          <td><%= user.sex %></td>

        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <p> <strong> You need to Login with us to see and update your details. </strong> </p>
  <%= link "Login",    to: "/login" %> <br>
  <%= link "Register", to: user_path(@conn, :new) %>
<% end %>

web/templates/user/new.html.eex
<h2> Fill Your details below: </h2>

<%= render "form.html", changeset: @changeset, action: user_path(@conn, :create) %>

<%= link "Return to Home", to: user_path(@conn, :index) %> 

web/templates/user/show.html.eex
<h3>Your Details</h3>
<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Age:</strong>
    <%= @user.age %>
  </li>

  <li>
    <strong>Sex:</strong>
    <%= @user.sex %>
  </li>

</ul>

<%= link "Update your account", to: user_path(@conn, :edit, @user), class: "btn btn-success btn-xs" %>&emsp;&emsp;&emsp;
<%= link "Logout your account", to: session_path(@conn, :delete), method: :delete, class: "btn btn-warning btn-xs" %>&emsp;&emsp;&emsp;
<%= link "Delete your account", to: user_path(@conn, :delete, @user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>